package org.opensrp.common.util;

public enum PermissionName {
	USER, ADD_USER, EDIT_USER, UPDATE_PASSWORD, ROLE, ADD_ROLE, EDIT_ROLE, VISIT_HOME, LOCATION_TAG, ADD_LOCATION_TAG, EDIT_LOCATION_TAG, TOPIC, ADD_TOPIC, EDIT_TOPIC, POURASAVA, ADD_POURASAVA, EDIT_POURASAVA, UNION, ADD_UNION, EDIT_UNION, PARA, ADD_PARA, EDIT_PARA, PARA_CENTER, ADD_PARA_CENTER, EDIT_PARA_CENTER, CLUSTER, ADD_CLUSTER, EDIT_CLUSTER, DISTRICT, ADD_DISTRICT, EDIT_DISTRICT, LOCATION, DIVISION, ADD_DIVISION, EDIT_DIVISION, UPAZILA, ADD_UPAZILA, EDIT_UPAZILA, ADD_DHIS2_ID, EDIT_DHIS2_ID, DHIS2, OTHER_MEETING_MINUTES_LIST, ADD_OTHER_MEETING_MINUTES, EDIT_OTHER_MEETING_MINUTES, WORK_MEETING_LIST, ADD_WORK_MEETING, EDIT_WORK_MEETING
}
